PEP-8
crwilcox/KinectHowOld pull request #3
Opened 2017-05-19 06:08 UTC by itsthejoker

The reasons for this PR are twofold:

1) Without PEP-8, I can't actually see the whole file on my laptop screen at once. This makes editing and contributing unnecessarily difficult.

2) Adhering to PEP-8, especially with demo material, is important for other contributors.

This PR *should* fix the PEP-8 and formatting issues. As I do not have a Kinect, I can't test the code myself; I've only made one actually major change to the flow, so I think it should work in its current configuration.

2017-05-19 17:07 UTC, crwilcox requested changes
Hey @itsthejoker, my coworker had edited the code that was running live with some easter egg changes. my guess is this may now have issues :(

The biggest help of this is definitely pulling this to the soylent method though. 

If you pull master and resolve those differences I can try this out on the demo box. It looks good to me :)

2017-05-19 17:34 UTC, itsthejoker commented
There are still a couple places where it can be refined further with some more methods for clarity; I don't want to change too much though, especially since I can't test it. Either way, conflicts are fixed.

2017-05-20 22:09 UTC, crwilcox commented
Thanks Joe. I plan to merge this and I can test and address issues in it. Thanks for contributing!

2017-05-20 22:09 UTC, crwilcox approved these changes

2017-05-20 22:09 UTC, merged